// Generated by Selenium IDE
const { Builder, By, Key } = require("selenium-webdriver");
import { timeout } from "../util/timeout";
describe("1_add_by_enter", function () {
  timeout(30000);
  let driver;
  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("1_add_by_enter", async function () {
    await driver.get("http://localhost:3000/");
    await driver.manage().window().setRect(1920, 1080);
    await driver.findElement(By.name("todo")).click();
    await driver.findElement(By.name("todo")).sendKeys("test add");
    await driver.findElement(By.name("todo")).sendKeys(Key.ENTER);
    await driver.close();
  });
});
