// Generated by Selenium IDE
const { Builder, By } = require("selenium-webdriver");
import { timeout } from "../util/timeout";
describe("2_add_by_click", function () {
  timeout(30000);
  let driver;
  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("2_add_by_click", async function () {
    await driver.get("http://localhost:3000/");
    await driver.manage().window().setRect(1920, 1080);
    await driver.findElement(By.name("todo")).click();
    await driver.findElement(By.name("todo")).sendKeys("test by click");
    await driver.findElement(By.css(".save-btn")).click();
    await driver.close();
  });
});
