// Generated by Selenium IDE
const { Builder, By } = require("selenium-webdriver");
import { timeout } from "../util/timeout";
describe("4_edit_by_click", function () {
  timeout(30000);
  let driver;
  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("4_edit_by_click", async function () {
    await driver.get("http://localhost:3000/");
    await driver.manage().window().setRect(1920, 1080);
    await driver
      .findElement(By.css(".root-container:nth-child(6) .toolkit-edit svg"))
      .click();
    await driver
      .findElement(
        By.css(".root-container:nth-child(6) button:nth-child(1) > p")
      )
      .click();
    await driver.findElement(By.name("todo")).click();
    await driver.findElement(By.name("todo")).click();
    await driver.findElement(By.name("todo")).sendKeys("test edit by click");
    await driver
      .findElement(By.css(".input-container:nth-child(6) .save-btn"))
      .click();
    await driver.close();
  });
});
