// Generated by Selenium IDE
const { Builder, By } = require("selenium-webdriver");
import { timeout } from "../util/timeout";
describe("7_check_and_uncheck_with_change_menu", function () {
  timeout(30000);
  let driver;
  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("7_check_and_uncheck_with_change_menu", async function () {
    await driver.get("http://localhost:3000/");
    await driver.manage().window().setRect(1920, 1080);
    await driver
      .findElement(By.css(".root-container:nth-child(5) .checkbox svg"))
      .click();
    await driver
      .findElement(By.css(".root-container:nth-child(6) .checkbox svg"))
      .click();
    await driver.findElement(By.css(".dropbtn")).click();
    await driver
      .findElement(By.css(".group > button:nth-child(2) > p"))
      .click();
    await driver
      .findElement(By.css(".root-container:nth-child(4) rect"))
      .click();
    await driver.findElement(By.css(".dropbtn > p")).click();
    await driver.findElement(By.css("button:nth-child(3) > p")).click();
    await driver
      .findElement(By.css(".root-container:nth-child(5) .checkbox svg"))
      .click();
    await driver.findElement(By.css(".dropbtn > p")).click();
    await driver
      .findElement(By.css(".group > button:nth-child(1) > p"))
      .click();
    await driver.close();
  });
});
