// Generated by Selenium IDE
const { Builder, By, Key } = require("selenium-webdriver");
import { timeout } from "../util/timeout";

describe("8_edit_delete_with_check_n_uncheck_change_menu", function () {
  timeout(30000);
  let driver;
  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("8_edit_delete_with_check_n_uncheck_change_menu", async function () {
    await driver.get("http://localhost:3000/");
    await driver.manage().window().setRect(1920, 1080);
    await driver
      .findElement(By.css(".root-container:nth-child(6) .edit"))
      .click();
    await driver
      .findElement(
        By.css(".root-container:nth-child(6) button:nth-child(1) > p")
      )
      .click();
    await driver.findElement(By.name("todo")).click();
    await driver.findElement(By.name("todo")).click();
    {
      const element = await driver.findElement(By.name("todo"));
      await driver.actions({ bridge: true }).doubleClick(element).perform();
    }
    await driver.findElement(By.name("todo")).sendKeys("Edit");
    await driver.findElement(By.name("todo")).sendKeys(Key.ENTER);
    await driver.findElement(By.css(".dropbtn")).click();
    await driver
      .findElement(By.css(".group > button:nth-child(2) > p"))
      .click();
    await driver
      .findElement(By.css(".root-container:nth-child(3) .toolkit-edit svg"))
      .click();
    await driver
      .findElement(By.css(".root-container:nth-child(4) .edit"))
      .click();
    await driver
      .findElement(
        By.css(".root-container:nth-child(3) button:nth-child(1) > p")
      )
      .click();
    await driver
      .findElement(
        By.css(".root-container:nth-child(4) button:nth-child(1) > p")
      )
      .click();
    await driver.findElement(By.name("todo")).click();
    await driver.findElement(By.name("todo")).click();
    {
      const element = await driver.findElement(By.name("todo"));
      await driver.actions({ bridge: true }).doubleClick(element).perform();
    }
    await driver.findElement(By.name("todo")).sendKeys("All Done");
    await driver
      .findElement(By.css(".input-container:nth-child(3) .save-btn"))
      .click();
    await driver.findElement(By.name("todo")).click();
    await driver.findElement(By.name("todo")).sendKeys("Done");
    await driver
      .findElement(By.css(".input-container:nth-child(4) .save-btn"))
      .click();
    await driver.findElement(By.css(".dropbtn")).click();
    await driver.findElement(By.css("button:nth-child(3) > p")).click();
    await driver
      .findElement(By.css(".root-container:nth-child(4) .checkbox svg"))
      .click();
    await driver.findElement(By.css(".dropbtn > p")).click();
    await driver
      .findElement(By.css(".group > button:nth-child(1) > p"))
      .click();
    await driver
      .findElement(By.css(".root-container:nth-child(5) .edit"))
      .click();
    await driver
      .findElement(By.css(".root-container:nth-child(6) .toolkit-edit svg"))
      .click();
    await driver
      .findElement(By.css(".root-container:nth-child(7) .toolkit-edit path"))
      .click();
    await driver
      .findElement(By.css(".root-container:nth-child(7) .color-delete > p"))
      .click();
    await driver
      .findElement(By.css(".root-container:nth-child(6) .color-delete > p"))
      .click();
    await driver
      .findElement(By.css(".root-container:nth-child(5) .color-delete > p"))
      .click();
    await driver.close();
  });
});
